### PR TITLE
chore(build): upgrade Go to 1.20.10

### PR DESCRIPTION
**Pull request by alespour**
Closes https://github.com/influxdata/edge/issues/509

  - [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] Any changes to `etc/Dockerfile_build` have been pushed to DockerHub, and the changes have been added to `.circleci/config.yml`

### CODE REVIEW

**Comment by alespour** [comment]
@jdstrand I've no idea how to satisfy checklist item `Any changes to etc/Dockerfile_build have been pushed to DockerHub, and the changes have been added to .circleci/config.yml`

**Comment by jdstrand** [comment]
> @jdstrand I've no idea how to satisfy checklist item Any changes to etc/Dockerfile_build have been pushed to DockerHub, and the changes have been added to .circleci/config.yml

@jeffreyssmith2nd or @bnpfeife - do you have details for this?

**Comment by jeffreyssmith2nd** [comment]
That will happen as part of the next full release, so not something that needs to be worried about in this PR.

**Comment by jdstrand** [comment]
> That will happen as part of the next full release, so not something that needs to be worried about in this PR.

Fyi just for clarity, we do want to cut a new chronograf release rather than just stage this PR's changes. However you get there is fine with me. :)

**Pull request merged**
