### PR TITLE
Add WhitelistOnly setting to organizations

### PR DESCRIPTION
**Pull request by desa**
This adds a parameter `WhitelistOnly` to organizations. This setting means that users must be explicitly added to an organization. Currently the only organization that this applies to is the DefaultOrganization. It prevents users who have authenticated from accessing the application without having been explicitly added by an admin or super admin.

In particular this manifests itself in `Me` where we check to see if the DefaultOrganization is WhitelistOnly. If DefaultOrganization is WhitelistOnly, then we do not create user in the default organization.

It is possible the while implementing #2217, we will end up refactoring this logic into the mapping logic.

- [x] Connect #2328
- [ ] Connect #2324
- [x] Connect #2210 
- [ ] Connect #2343

### CODE REVIEW

**Comment by jaredscheib** [comment]
This will need the client side done per https://github.com/influxdata/chronograf/issues/2343 before this can be considered mergeable.

**Comment by alexpaxton** [comment]
Committed some UI for a whitelist toggle in the orgs table. Currently is only in `OrganizationsTableRowDefault`

See line 20, the `SlideToggle` needs a real function passed into `onToggle`

screen shot 2017-11-10 at 2 14 04 pm
screen shot 2017-11-10 at 2 14 00 pm

**Comment by jaredscheib** [comment]
Awesome -- thanks @alexpaxton! Only in Default org is appropriate, since that's the only org that it's valid for, for now.

**Comment by alexpaxton** [comment]
@jaredscheib I kept the header as `Whitelist` otherwise it feels visually too spacious. I added the `?` helper tooltip to make up the difference. If the move is to make the column heading longer then I would say do away with the tooltip

**Comment by alexpaxton** [comment]
Could also use "Private" instead of "Whitelist" as that suggests users can't join on their own

**Comment by jaredscheib** [comment]
@lukevmorris suggested `Public`, and I'm a big fan. Let's go with that :)

**Comment by lukevmorris** [comment]
Closing in favor of #2354

**Pull request closed without merging**
