### PR TITLE
fix(build): rename arm rpms with yum-compatible names

### LINKED ISSUE #5790: Rename Chronograf armhf and arm64 rpms
The Chronograf arm64 rpm is named in a way that is incompatible with Yum. In the RedHat world, arm64 is called aarch64, and armhf is called armv7hl.

See [this issue in the build-scripts repository](https://github.com/influxdata/build-scripts/issues/6), as well as [a pair](https://github.com/influxdata/influxdb/pull/21749) of [PRs](https://github.com/influxdata/influxdb/pull/21775) to influxdb that change the way the rpm is named. Making this change in chronograf would allow the package to be in line with influxdb and telegraf in how arm architectures are handled by yum.

### PR DESCRIPTION
**Pull request by sranka**
Fixes #5790 

Follow-on for influxdata/influxdb#21749

  - [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] Any changes to `etc/Dockerfile_build` have been pushed to DockerHub, and the changes have been added to `.circleci/config.yml`

### CODE REVIEW

**Comment by sranka** [comment]
@ivankudibal  a build script has changed in this PR. Please build and push a new docker build image as you lastly did in https://github.com/influxdata/chronograf/pull/5754.

**Review by ivankudibal — APPROVED** [review]
ok

**Comment by ivankudibal** [comment]
> > ok
> 
> A build script has changed in this PR. @ivankudibal Can you please [build and push a new docker image](https://github.com/influxdata/chronograf/blob/master/etc/README.md) as you lastly did for #5754.

I have pushed a new build image from this branch, the image appears to have as same sha1 as the previous build image

**Comment by sranka** [comment]
@ivankudibal the new distributions appear properly in nightly builds:

```
Uploading /home/circleci/project/build/linux/arm64/chronograf-nightly.aarch64.rpm (32 MB): DONE
Uploading /home/circleci/project/build/linux/armhf/chronograf-nightly.armv7hl.rpm (31 MB): DONE
```

**Pull request merged**
