### PR TITLE
Fixes #1077 by removing win_system and system from the select query.

### LINKED ISSUE #1077: Chronograf requires users to run Telegraf's CPU and system plugins to ensure that all Apps appear on the HOST LIST page.
Probably a dupe of #1003

### PR DESCRIPTION
**Pull request by ndrone**
Added Avg Ping to hosts table

Added last packet loss capture

Updated status to check the ping statistics when the cpu statistics are not available. Before marking the host as down.

  - [x ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x ] Rebased/mergable
  - [x ] Tests pass
  - [x ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Connect #

### CODE REVIEW

**Comment by ndrone** [comment]
Anybody going to merge this?

**Comment by goller** [comment]
Hi there @ndrone, sorry it took so long to get to this!

Overall I like it a lot.  Do you mind breaking the PR into two?  The first would be the changes for
```show tag values with key = "host"',``` and the second woudl be the ping?

The tag values with key will merge right away.  However, for ping would you be able to make it an optional column if the data doesn't exist?

**Comment by ndrone** [comment]
No problem breaking it up into 2. This PR is ready to go with just the host change. I'll create another PR for the ping here shortly.

**Comment by goller** [comment]
Hi @ndrone, yup! hiding rather than N/A

(I'll fix this CHANGELOG.md conflict and merge now)

**Comment by goller** [comment]
@ndrone merged! thank you so much!

**Pull request merged**
