### PR TITLE
database and retention policy swagger doc RFC

### PR DESCRIPTION
**Pull request by jademcgough**
This PR contains API documentation for the database and retention policy APIs. This isn't meant to be merged, but is a request for review before I implement them.

### CODE REVIEW

**Comment by jademcgough** [comment]
ref #1005

**Comment by goller** [comment]
@jademcgough let's make sure there are links in this design as well.  Beyond having self, the database should probably have a link to rps.

**Comment by jademcgough** [comment]
@goller will do, thanks

**Comment by jademcgough** [comment]
I've merged this into #1029, closing this PR.

**Pull request closed without merging**
