### PR TITLE
Add support for Auth0 organizations

### PR DESCRIPTION
**Pull request by timraymond**
Users were previously unable to categorize Auth0 users into organizations like
they have been able to with other OAuth2 providers, like Github, Google, and
Heroku. This limits the usefulness of the Auth0 integration.

Unlike other providers, Auth0 allows greater flexibility in what is returned to
applications. Many plugins exist which modify Auth0's responses. Knowing this,
it was important to adopt something light-weight which could be supported both
by human administrators as well as automation.

This requires operators to configure Auth0 to apply an "organization" key to
each user in the "app_metadata" section of each of their users ("app_metadata"
is read-only by users). The value of this key should be a string identifying
the organization that the user belongs to. This can either be done manually, or
automatically through the use of Auth0 Rules. The organization that is allowed
to access Chronograf should then be supplied as either the command line flag
`--auth0-organizations="biffs-gang"` or the ENV:
`AUTH0_ORGANIZATIONS=biffs-gang`. Multiple organizations can be supplied to the
ENV option only by separating organizations with a comma. For example,
`AUTH0_ORGANIZATIONS=biffs-gang,time-travelers`

Additional test coverage was added because the PrincipalID method had to be
overridden to support organizations.

Connect #1554

### CODE REVIEW

**Comment by jademcgough** [comment]
Awesome, was wondering how we'd verify whether someone had permissions to view a chronograf app.

**Comment by nhaugo** [comment]
@lukevmorris to give a try tomorrow

**Comment by lukevmorris** [comment]
Tested, works as expected. To be optimized later:
Since we do organization verification on our server, if a user provides correct credentials but is associated with an incorrect organization, auth0 will count it as a successful login. Ideally we should find a way to ask auth0 to "verify that the user has this value in app_metadata.organization"

**Comment by lukevmorris** [comment]
After the build passes on circleci, I think this is safe to merge

**Comment by timraymond** [comment]
As mentioned out-of-band, I think the organization validation thing can probably be done with Auth0 Rules, since there's wide flexibility to reject logins under arbitrary conditions.

**Pull request merged**
