### PR TITLE
chore: upgrade to NodeJS >= 12

### PR DESCRIPTION
**Pull request by m1cr0man**
_What was the problem?_

Installing the project dependencies and building the project was failing because the version of nan that deasync depended on, that in turn parcel depended on, was not compatible with NodeJS > 12.

_What was the solution?_

Upgrading parcel.

  - [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [X] Rebased/mergeable
  - [X] Tests pass
  - [X] Any changes to `etc/Dockerfile_build` have been pushed to DockerHub, and the changes have been added to `.circleci/config.yml`
  - [ ] swagger.json updated (if modified Go structs or API)
  - [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by m1cr0man** [comment]
Would there be interest in upgrading all the UI dependencies? I've been having trouble each time I upgrade my system's node version and rebuilding the package for one reason or another. I was tempted to do it now but this fix alone is essential.

**Comment by sranka** [comment]
Thank you @m1cr0man , can you please also upgrade .nvmrc and CONTRIBUTING.MD .

**Review by sranka — CHANGES_REQUESTED** [review]
Thank you @m1cr0man , can you please also update .nvmrc and CONTRIBUTING.md ?

**Comment by m1cr0man** [comment]
@sranka Apologies for taking so long, that is done now :) I rebuilt the yarn.lock from master since there was some merge conflicts with it, and fixing them by hand seemed like a bad idea

**Comment by sranka** [comment]
@m1cr0man thank you for your time herein, I just created a similar #5578 that simply resolves conflicts in yarn.lock, CHANGELOG.md. I also have to check whether the builds are ok.

**Comment by m1cr0man** [comment]
Thanks @sranka , good to see Node updated! It will make deployment on NixOS much easier for me and others :)

**Pull request closed without merging**
