### PR TITLE
UX Improvements

### PR DESCRIPTION
**Pull request by alexpaxton**
- [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Connect #1990 
Connect #1985 
Connect #1964 
Connect #1965 

### The Problem
- Too easy to delete a cell, prone to accidental deletions
- Sort on database list (schema explorer) is not ideal
- Context menu feels like too many clicks for just housing `Edit`/`Delete`/`Rename`
- `Rename` is not used often enough to justify its placement

### The Solution
- [x] Require second click confirmation to delete a cell
- [x] Sort database list alphabetically by database name
- [x] Expose all options in context menu as buttons with icons
- [x] Move `Rename` functionality into Cell Editor Overlay

### Preview
confirm-delete-cell-3
Require a second click to delete a cell

screen shot 2017-09-20 at 7 17 11 pm
No more dropdown, just icons

screen shot 2017-09-20 at 7 18 42 pm
Plays nice with custom time indicators

screen shot 2017-09-20 at 7 19 32 pm
Moved rename here. If the user edits the name input they can hit `Escape` which reverts their change, or they can hit `Enter` or manually blur which pushes the new name into the CEO's working name state. Clicking the green checkmark button saves the CEO's working name state. Shout out to @cryptoquick for help implementing this logic. I decided to add this interaction in because it felt odd to have nothing happen when you hit `Enter` or `Escape`

### CODE REVIEW

**Comment by alexpaxton** [comment]
Thinking that it might make sense to move the code for #1989 to a different PR, as it appears there is a much larger amount of work to make that happen

**Comment by alexpaxton** [comment]
Moved the work done for #1989 into this PR: #2002

**Comment by alexpaxton** [comment]
@cryptoquick I opted to not have a separate save for the name field. I think it introduces too much confusion. For example, if I edit a cell, change the name, then click the grey `X` button I would expect none of my changes to save and then I would see that the name changed. It would make me wonder what information the save button actually saves, or that something had gone wrong.

The user would have to click the green checkmark to confirm their changes, even if just a name change, so I have the name grouped with all the other items in the cell editor.

That being said, an alternative UX would be to have separate save buttons for each aspect of the cell editor

**Comment by cryptoquick** [comment]
@alexpaxton I see. Well, what if the input was blurred by enter or esc?

**Comment by alexpaxton** [comment]
@cryptoquick On it like PB on J. It does feel odd that nothing happens when you hit `Enter` or `Escape`

**Comment by cryptoquick** [comment]
Looks and works great! 👍

**Pull request merged**
