### PR TITLE
Add insecure ssl support to connect to kapacitor

### PR DESCRIPTION
**Pull request by goller**
- [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Connect #2139

### The problem
No support for insecure, self-signed certificates for https connections to kaapcitor

### The Solution
Added `insecureSkipVerify` to the kapacitor REST interface

### CODE REVIEW

**Comment by binary0111** [comment]
Something still seems broken, wether I add Kapacitor from the cmdline using `--new-sources` or manually POST to chronograf.

```
# chronograf -v
2017/11/24 04:39:30 Chronograf 1.2.0~n201711230837 (git: 944030d0f17fa50d7d7d6dd58dc8f526c1895bba)
```

```
# curl -X POST -H "Content-Type: application/json" -d '{"name":"kapa_test", "url":"https://localhost:9092", "insecureSkipVerify":true, "active":true}' http://localhost:8888/chronograf/v1/sources/1/kapacitors
{"id":"2","name":"kapa_test","url":"https://localhost:9092","insecureSkipVerify":true,"active":true,"links":{"proxy":"/chronograf/v1/sources/1/kapacitors/2/proxy","self":"/chronograf/v1/sources/1/kapacitors/2","rules":"/chronograf/v1/sources/1/kapacitors/2/rules","tasks":"/chronograf/v1/sources/1/kapacitors/2/proxy?path=/kapacitor/v1/tasks","ping":"/chronograf/v1/sources/1/kapacitors/2/proxy?path=/kapacitor/v1/ping"}}
```

In chronograf's log:

```
2017/11/24 04:29:52 http: proxy error: x509: certificate is valid for test_box, not localhost
2017/11/24 04:30:34 http: proxy error: x509: certificate is valid for test_box, not localhost
```

In Kapacitor's log:

```
log messages must have 'L!' prefix where L is one of 'D', 'I', 'W', 'E'[log] 2017/11/24 04:29:52 http: TLS handshake error from 127.0.0.1:36122: remote error: tls: bad certificate
log messages must have 'L!' prefix where L is one of 'D', 'I', 'W', 'E'[log] 2017/11/24 04:30:34 http: TLS handshake error from 127.0.0.1:36154: remote error: tls: bad certificate
```

**Comment by binary0111** [comment]
@goller any hints here? :)

**Comment by goller** [comment]
@binary0111 hey there! Just before I went on vacation @desa and I were looking at that new sources code ... it doesn’t quite respect the changes I made in this pr but it should. We will need to fix it.

Would you open a new issue about the new sources option ?

**Comment by binary0111** [comment]
@goller there is already an open issue #2139 for this.

From you earlier comment on #1653 :

> I've added the tracking issue for kapacitor insecure ssl here: #2139
> I've added support in the chronograf REST server here: #2140 

Do you want me to open a separate issue or will #2139 suffice?

**Comment by goller** [comment]
Ah yes, thank you @binary0111 !

I've just added PR #2689 to fix this.

**Comment by binary0111** [comment]
Thanks @goller! Much Appreciated :)

**Pull request merged**
