### PR TITLE
Fix optin cursor

### PR DESCRIPTION
**Pull request by alexpaxton**
- [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Connect #1877 

### The Problem
The app was literally unusable:

### CODE REVIEW

**Comment by lukevmorris** [comment]
Merged master into this branch to resolve pending merge conflicts

**Comment by alexpaxton** [comment]
@lukevmorris I did the thing!

**Comment by jaredscheib** [comment]
Nice! Looks good, but should the mouse be a pointer sometimes when over `auto`?
cursor

**Comment by lukevmorris** [comment]
Current behavior is that your cursor is a pointer when you have something to click. If auto is blue, then clicking it will do nothing.

**Comment by 121watts** [comment]
@jaredscheib if memory serves, the default cursor when `auto` is already selected was intentional.  i.e. when auto is already selected we don't want to draw the user to the `auto` text to turn it off.  I don't mind it either way, but I think that was decision at the time.

**Comment by jaredscheib** [comment]
All right. I think it's slightly misleading, as it made me wonder if I could ever click it. Most likely the handler does fire for it even if you click it then with the mouse pointer. But either way is fine – I'll defer to @alexpaxton, and otherwise :shipit:

**Comment by alexpaxton** [comment]
opt-in-polish

Opted for (no pun intended) this kind of interaction. The cursor is always `pointer` which makes it unmistakeable that the label can be clicked. However, if it is toggled (blue) it simply lights up a bit but doesn't do anything. This subtle but crucial feedback lets the user know the component is working correctly but that their action does not do anything.

**Comment by jaredscheib** [comment]
Pulled down and tested. Looks great! Thanks @alexpaxton :) :shipit:

**Pull request merged**
