### PR TITLE
fix(schema-explorer): update the flux schema explorer to use v1 package

### PR DESCRIPTION
**Pull request by desa**
Closes https://github.com/influxdata/chronograf/issues/5316

_What was the problem?_
Flux started erroring on a query that used to work.

_What was the solution?_
Use the v1 package.

  - [x] CHANGELOG.md updated with a link to the PR (not the Issue)

### CODE REVIEW

**Comment by desa** [comment]
@karel-rehor can you test this branch to make sure that it solves the issue it claims to.

**Comment by karel-rehor** [comment]
@desa 
I built it locally and it looks like it works. 👍

```
karl@algonquin:~/prjs/osobni/go/src/github.com/influxdata/chronograf$ git branch
* fix/flux-schema-explorer
  master
karl@algonquin:~/prjs/osobni/go/src/github.com/influxdata/chronograf$ git status
On branch fix/flux-schema-explorer
Your branch is up-to-date with 'origin/fix/flux-schema-explorer'.
nothing to commit, working directory clean
karl@algonquin:~/prjs/osobni/go/src/github.com/influxdata/chronograf$ make
cd ui && yarn --no-progress --no-emoji
yarn install v1.19.1
[1/4] Resolving packages...
...
```
and then 
```
karl@algonquin:~/prjs/osobni/go/src/github.com/influxdata/chronograf$ ./chronograf 
INFO[0000] Running migration 59b0cda4fc7909ff84ee5c4f9cb4b655b6a26620 
INFO[0000] Serving chronograf at http://[::]:8888        component=server
INFO[0000] Reporting usage stats                         component=usage freq=24h reporting_addr=https://usage.influxdata.com stats=os,arch,version,cluster_id,uptime
INFO[0025] Serving assets                                component=server method=GET remote_addr=[::1]:44194 url=/
INFO[0025] Response: OK                                  component=server method=GET remote_addr=[::1]:44194 response_time=2.328735ms status=200
INFO[0025] Serving assets                                component=server method=GET remote_addr=[::1]:44194 url=/src.fb75381a.css
INFO[0025] Serving assets                                component=server method=GET remote_addr=[::1]:44196 url=/src.b1c00f50.js
...
```
After starting the test cluster with telegraf I'm able to navigate the schema as shown in the screenshot below

Data-Explorer-Flux-Fix01

**Comment by karel-rehor** [comment]
@desa 

I built it locally, checked it manually and ran some tests.  It looks like it works. 

Built it.. 
```
karl@algonquin:~/prjs/osobni/go/src/github.com/influxdata/chronograf$ git checkout fix/flux-schema-explorer
Branch fix/flux-schema-explorer set up to track remote branch fix/flux-schema-explorer from origin.
Switched to a new branch 'fix/flux-schema-explorer'
karl@algonquin:~/prjs/osobni/go/src/github.com/influxdata/chronograf$ git branch
* fix/flux-schema-explorer
  master
karl@algonquin:~/prjs/osobni/go/src/github.com/influxdata/chronograf$ git status
On branch fix/flux-schema-explorer
Your branch is up-to-date with 'origin/fix/flux-schema-explorer'.
nothing to commit, working directory clean
karl@algonquin:~/prjs/osobni/go/src/github.com/influxdata/chronograf$ make
cd ui && yarn --no-progress --no-emoji
yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
...
```
Started it against the test cluster
```
karl@algonquin:~/prjs/osobni/go/src/github.com/influxdata/chronograf$ ./chronograf 
INFO[0000] Running migration 59b0cda4fc7909ff84ee5c4f9cb4b655b6a26620 
INFO[0000] Serving chronograf at http://[::]:8888        component=server
INFO[0000] Reporting usage stats                         component=usage freq=24h reporting_addr=https://usage.influxdata.com stats=os,arch,version,cluster_id,uptime
INFO[0025] Serving assets                                component=server method=GET remote_addr=[::1]:44194 url=/
INFO[0025] Response: OK                                  component=server method=GET remote_addr=[::1]:44194 response_time=2.328735ms status=200
INFO[0025] Serving assets                                component=server method=GET remote_addr=[::1]:44194 url=/src.fb75381a.css
INFO[0025] Serving assets                                component=server method=GET remote_addr=[::1]:44196 url=/src.b1c
```
Manually verified schema navigation. 

Data-Explorer-Flux-Fix01

Ran core flux tests against it 

Build_Flux_Results

**Comment by desa** [comment]
@karel-rehor awesome! Thank you!

**Pull request merged**
