### PR TITLE
chore(build): upgrade golang to 1.18.4

### LINKED ISSUE #5989: Please upgrade golang to 1.18.4 for security fixes
https://groups.google.com/g/golang-announce/c/nqrv9fbR0zE announced 1.18.4 for several security issues. I've not yet determined if those fixes are relevant for `chronograf`, but since `chronograf` was recently updated to 1.18.3 in preparation for `chronograf` 1.9.4, it would be nice to recompile and release 1.9.5 with 1.18.4 if possible.

### PR DESCRIPTION
**Pull request by sranka**
Closes #5989 

This PR upgrades golang to 1.18.4

  - [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] Any changes to `etc/Dockerfile_build` have been pushed to DockerHub, and the changes have been added to `.circleci/config.yml`

### CODE REVIEW

**Comment by sranka** [comment]
@ivankudibal this PR requires a new build image to be ready for review - https://github.com/influxdata/chronograf/blob/master/etc/README.md

**Comment by ivankudibal** [comment]
[✔] Step 1: Build New Docker Image and Save It to Quay

**Comment by sranka** [comment]
> [heavy_check_mark] Step 1: Build New Docker Image and Save It to Quay
> 
> chronograf-20220721: digest: sha256:aaa86c015ef521b4d835cd51b3a0222f4f39e4e4b2a82ee1d30b3f7c6f85b8a3 size: 2007

New builder image applied, thx, please review & approve

**Review by ivankudibal — APPROVED** [review]
thank you

**Pull request merged**
