### PR TITLE
IE11 fix - Promise is Undefined

### PR DESCRIPTION
**Pull request by theone3nu**
Closes #

_Briefly describe your proposed changes:_
_What was the problem?_ In IE 11 Charts are not opening. Error Promise is Undefined and fetch is undefined.
_What was the solution?_ Added import 'babel-polyfill' in worker.ts and import 'isomorphic-fetch' in worker/jobs classes.

  - [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] swagger.json updated (if modified Go structs or API)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by nhaugo** [comment]
Hi @theoDiefenthal would you mind adding a changelog entry to the 1.7.6 bug fix section, you may need to rebase.

**Comment by theoDiefenthal** [comment]
@nhaugo I think you wanted to refer to @theone3nu , not me. So I just link him in this comment... :)

**Comment by nhaugo** [comment]
Hi @theone3nu would you mind adding a changelog entry to the 1.7.6 bug fix section, you may need to rebase.

Thanks @theoDiefenthal

**Comment by theone3nu** [comment]
@nhaugo Can you tell me how to add changelog entry and from where i can get it. I just pushed my changes and created pr.

**Comment by theone3nu** [comment]
@nhaugo Just pushed changelog. Please check and merge the changes. Thanks

**Pull request closed without merging**
