### PR TITLE
Polish Alerts Page Design

### PR DESCRIPTION
**Pull request by alexpaxton**
- [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Connect #2749 

### The Problem
- Delete / Edit buttons do not follow the *appear on hover* pattern seen in other tables
- TICKscripts do not follow the *click name to edit* pattern seen in the rules table
- Alert Rules do not show in TICKscripts table even though they are technically TICKscripts beneath the surface
- Delete buttons do not require confirmation
- The name of the page in the page header does not match the side nav
- Unclear what the difference between TICKscripts and Alert Rules is

### The Solution
- Delete buttons only appear on row hover and require confirmation
- Removed the `Edit TICKscript` button from both tables
- TICKscript names are links that take you to the editor (matches pattern found in Alert Rules table)
- TICkscripts table shows both Alert Rules and TICKscripts (although it shows the `name` instead of `id` for Alert Rules
  - This modifies the UX such that if the user wants to edit an Alert Rule as a TICKscript they must locate it in the TICKscripts list and click the name there
- TICKscripts are color coded green because all things Kapacitor are usually green
- Changed the name of the page to `Manage Alerts` in both the page header and sidenav
- Should be more clear that all Alert Rules are TICKscripts but not all TICKscripts are Alert Rules
- Will be more straightforward to selectively show each table based on permissions
- Improved the column widths and removed monotype text

### Preview
screen shot 2018-02-20 at 2 04 08 pm

screen shot 2018-02-20 at 2 05 36 pm

screen shot 2018-02-20 at 2 19 48 pm

### CODE REVIEW

**Comment by alexpaxton** [comment]
screen shot 2018-02-22 at 6 12 45 pm

Changed the tickscript table to show `id` and `name`

**Comment by alexpaxton** [comment]
screen shot 2018-02-23 at 9 55 39 am
Added a handy tooltip

screen shot 2018-02-23 at 9 55 28 am
Changed name of page to refer to the items as "Tasks"

screen shot 2018-02-23 at 9 55 32 am
Having items referred to as "Tasks" in both tables helps cement the concept

screen shot 2018-02-23 at 9 59 53 am
Removed the `ID` column in favor of just showing `Name` in both tables

**Comment by russorat** [comment]
i love all of this! 💯

**Comment by ebb-tide** [comment]
The one thing that stuck out to me was that I think the "Manage Tasks" is the more primary purpose of the Alerts section Could that be above history?

**Comment by alexpaxton** [comment]
@ebb-tide just made the switch

**Pull request merged**
