### PR TITLE
Fail continuous integration upon JS & TS linter errors and TS check errors

### LINKED ISSUE #3996: Add linting and type-checking to continuous integration flow

### PR DESCRIPTION
**Pull request by jaredscheib**
Closes #3996 

_Briefly describe your proposed changes:_
_What was the problem?_
Our continuous integration process did not take JavaScript linting, TypeScript linting, and TypeScript errors into account.

_What was the solution?_
Fail CI if any linter or TS errors occur.

  - [ ] Rebased/mergeable
  - [ ] Tests pass

### CODE REVIEW

**Comment by chnn** [comment]
we'll have to fix all the linting errors before merging this. Kinda painful because it introduce merge conflicts for everyones current feature branches, but I don't see any way around that.

**Comment by jaredscheib** [comment]
actually, this PR won't even pass given the new rule ;) so part of this PR will need to be to fix all of those errors. i'm happy to do this when i'm back.

**Comment by chnn** [comment]
@jaredscheib Turns out that we didn't have any true ESLint or TSLint errors. We had our prettier dependency specified as `^1.11.1`. Previously this resolved to `1.12.1`, but with the recent package.json changes it resolved to `1.13`. Prettier introduces “breaking” style changes in semvar minor releases, which why we then saw a bunch of TSLint and ESLint errors. I locked down prettier to `1.12.1` (what we have been using for a while) to resolve the issue.

We still, however, had type checking errors. I resolved those.

**Comment by jaredscheib** [comment]
Good catch, @chnn! All looks good to me. Let's get a review / approval from someone who hasn't worked on this PR.

**Comment by lukevmorris** [comment]
Seems fine to me, and it looks like it's working in CI:
```
$ eslint src
Done in 7.30s.
yarn run v1.5.1
$ tslint -c ./tslint.json '{src,test}/**/*.ts?(x)'
Done in 24.96s.
yarn run v1.5.1
$ tsc -p ./tsconfig.json --noEmit --pretty
Done in 12.18s.
```

**Pull request merged**
