### PR TITLE
chore(build): upgrade golang to 1.18.6

### LINKED ISSUE #5995: Please upgrade golang to 1.18.5 for security fix
https://groups.google.com/g/golang-announce/c/YqYYG87xB10/m/NzQjeXshBAAJ announced 1.18.5 for a security issue. I've not yet determined if that fix is relevant for chronograf, but it would be nice to recompile and upgrade to 1.18.5 before the next release.

Thanks!

### PR DESCRIPTION
**Pull request by sranka**
Closes #5995 

This PR upgrades golang to 1.18.5

  - [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [ ] [Well-formatted commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)
  - [ ] Rebased/mergeable
  - [ ] Tests pass
  - [ ] Any changes to `etc/Dockerfile_build` have been pushed to DockerHub, and the changes have been added to `.circleci/config.yml`

### CODE REVIEW

**Comment by sranka** [comment]
@ivankudibal this PR requires a new build image to be ready for review - https://github.com/influxdata/chronograf/blob/master/etc/README.md

**Comment by jdstrand** [comment]
@sranka - hey, curious on the status of this? (also, thanks for working on it! :) )

**Comment by sranka** [comment]
> @sranka - hey, curious on the status of this? (also, thanks for working on it! :) )

we will resume working on security fixes before the next chronograf release, it is not a priority now

**Comment by jdstrand** [comment]
FYI, 1.18.7 has since been released.

**Comment by jdstrand** [comment]
@jeffreyssmith2nd - 1.18.9 has since been released and is the latest 1.18 release with security fixes. Please note that 1.18 is EOL now and 1.19.6 is has all the fixes. It is fine to update to 1.19 in two different steps if that is easier (1.18.9/1.18.10 then 1.19.6). Or feel free to go straight to 1.19.6.

**Comment by sranka** [comment]
Closed in favor of #6026

**Pull request closed without merging**
