### PR TITLE
Refactor server to issue 403s instead of 401s; handle 403s & routing in client; remove source Role concept

### PR DESCRIPTION
**Pull request by desa**
- [x] Connect #2393
- [x] Connect #2434 
- [x] Connect #2264 
- [x] Connect #2379 
- [x] Connect #2465
- [x] Update PR problem & solution accordingly

### Problem
1. If a user's current organization was deleted, we gave a rather opaque  500 internal server error with message `"Unknown error: organization not found"`
1. `AuthorizedUser` returned 401s, which was incorrect.
1. Miscommunication in #1915 caused us to add the concept of a minimum Role to sources. This was invalid.
1. When a user's role or superAdmin status was demoted, they should be routed to Purgatory or logged out accordingly
1. When a user's current organization was deleted, they should be logged out
1. When a superAdmin was only a member of an organization, they could not login from Purgatory

### Solution
1. If a user's current organization is not found, return a 403 with message `user's current organization was not found`.
1. Respond with 403s upon `AuthorizedUser`. This signals to the front end that a user must go through another auth flow – the client will log them out.
1. Remove the concept of Role on a source. All users have access to all sources within an Organization, except for Members, who cannot access sources.
1. Route the user to either /purgatory or /login when they are demoted to an insufficient role or superAdmin status, or when their current organization is deleted
1. Make sure superAdmins can log in from Purgatory

### CODE REVIEW

**Comment by jaredscheib** [comment]
Heads up, I'm getting a 404 not found with that error message

**Comment by jaredscheib** [comment]
I've added two more issues to this, since it's all in the same scope. These are all client-side fixes.

**Comment by jaredscheib** [comment]
- [ ] if you are in Purgatory after being removed from the Default organization, and then your user is deleted, you should be logged out

**Comment by alexpaxton** [comment]
Tackled #2465 

screen shot 2017-12-01 at 4 27 09 pm

**Comment by alexpaxton** [comment]
Telegraf* not telegraph ugh autocorrect

**Comment by jaredscheib** [comment]
Looks great - thanks!

**Comment by lukevmorris** [comment]
🎉

**Comment by jaredscheib** [comment]
In summary, this PR accomplished the following:
1. Serve 403s instead of 401s in response to unauthorized requests
1. comprehensively handle those responses appropriately in the client via prevention or rerouting & notifications
1. remove the concept of role from sources
1. handle demotion and promotion of role or superAdmin status gracefully in app and Purgatory
1. allow superAdmin-members to log in from Purgatory

**Pull request merged**
