### PR TITLE
Fix y-axis graph padding

### PR DESCRIPTION
**Pull request by jaredscheib**
- [ ] CHANGELOG.md updated
  - [x] Rebased/mergable
  - [x] Tests pass
  - [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Connect #881 

### The problem
Graph did not properly display highlighted range when value for "greater than" rule exceeded local data peak value. This bug also showed up in "inside range" and "outside range".

### The Solution
* Fixed the math for adding and subtracting padding.
* Removed incorrect and arbitrary "top" argument to allow "range" rules to display correct highlighting regardless of which value was greater.

Fixed display for "greater than":
screen shot 2017-02-15 at 1 46 14 am

### CODE REVIEW

**Comment by jaredscheib** [comment]
Cool, thanks! Getting to tests now and will come back with something.

**Comment by jaredscheib** [comment]
@121watts I added a couple of preliminary tests for your perusal.

Questions:
Maybe I should be generating random values?
Maybe multiple assertions should be in multiple tests?
Maybe the description is unclear?
Maybe the variable names aren't great?

**Comment by 121watts** [comment]
@jaredscheib Once you update the CHANGELOG this is good to merge!

**Comment by jaredscheib** [comment]
Cool, done! @121watts I'll leave it to you on this one~

**Pull request merged**
