### PR TITLE
Improve Sources Nomenclature

### PR DESCRIPTION
**Pull request by alexpaxton**
- [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergable
  - [ ] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Connect #2686 

### The Problem
- Our current terminology surrounding InfluxDB connections is hazy
- It seems like you can modify an InfluxDB instance when you can only connect to it

### The Solution
- Rename `Source` to `Connection` as suggested in the issue
- Rename `Kapacitor Config` to `Kapacitor Connection`

### Preview
screen shot 2018-01-11 at 1 46 05 pm
screen shot 2018-01-11 at 1 44 38 pm
screen shot 2018-01-11 at 1 44 27 pm
screen shot 2018-01-11 at 1 44 12 pm
screen shot 2018-01-11 at 1 46 53 pm

### CODE REVIEW

**Comment by alexpaxton** [comment]
@jaredscheib I am confused as to whether I should rename Kapacitor Configs as well?

**Comment by jaredscheib** [comment]
@alexpaxton how about `Add Kapacitor connection`? i don't think you need to use the words Source and Server, but you could.

three other things as well:
1) what if at the top of the `Add a New Connection` page, it said `Add a New InfluxDB Connection`?
1) same with the current KapacitorConfig page --> `Configure Kapacitor Connection`
1) could you edit the `Edit Source` page to reflect this similar approach?

**Comment by alexpaxton** [comment]
- Using consistent language between Kapacitor and InfluxDB connections:
  - Edit mode says "Configure Connection"
  - Creation says "Add a New Connection"
- Updated error and success alerts to reflect the name changes
- Renamed `Kapacitor Config` to `Kapacitor Connection`

**Comment by russorat** [comment]
I agree that the idea of connections makes sense here. I would suggest the following changes, but none are blockers:
 * "InfluxDB Connections" page title changed to just "Connections", since this page has all connections on it, not just InfluxDB ones.
 * "Connection Name & Host" changed to "InfluxDB Connection", i don't think it's necessary to call out specifically what we show in that column, just that it's the InfluxDB Connection

**Comment by alexpaxton** [comment]
screen shot 2018-01-12 at 12 02 32 pm

@russorat check it

Gonna merge this one once it's green

**Comment by jaredscheib** [comment]
looks good to me, though it could be that the blue button says `Add InfluxDB Connection` to be super clear.

**Comment by russorat** [comment]
@alexpaxton LGTM

**Pull request merged**
