### PR TITLE
1.7.x

### PR DESCRIPTION
**Pull request by theone3nu**
Closes #

_Briefly describe your proposed changes:_
_What was the problem?_ 
In IE 11 Charts are not opening because of Promise is Undefined
_What was the solution?_ Imported babel-polyfill library in worker.js and isomorphic-fetch promise in worker folder classes.
Files modified 
1) src/worker/worker.ts
2) src/worker/jobs/postJSON.ts
3) src/worker/jobs/proxy.ts
4) src/worker/jobs/get.ts
5) package.json
[ie11fixes.zip](https://github.com/influxdata/chronograf/files/2686271/ie11fixes.zip)

### CODE REVIEW

**Comment by bthesorceror** [comment]
@theone3nu thank you for the contribution. However, our workflow for this project is for contributors to create PRs based on `master` that we can merge into master and then pull changes into our release branches i.e. `1.7.x`. It would be greatly appreciated if you could make a PR in that fashion that we could review.

**Comment by theone3nu** [comment]
@bthesorceror I am unable to create pr in master branch. Can you please tell me the steps to create pr in master branch?

**Comment by bthesorceror** [comment]
@theone3nu the easiest way this is to fork the project and make the changes on your local repo then make a PR back to our repo from your local repo. For more reference here is our contributing repo https://github.com/influxdata/chronograf/blob/master/CONTRIBUTING.md#submitting-a-pull-request.

**Comment by theone3nu** [comment]
@bthesorceror Thanks. Just created PR. Please review and merge. Thanks.

**Pull request closed without merging**
