### PR TITLE
Make overlay technology full screen

### PR DESCRIPTION
**Pull request by alexpaxton**
- [x] CHANGELOG.md updated
- [x] Rebased/Mergable
- [x] Tests pass

No reason why this can’t or shouldn’t be done, it is a modal after all

### Screenshots
screen shot 2017-05-03 at 3 44 50 pm
screen shot 2017-05-03 at 3 44 54 pm

### CODE REVIEW

**Comment by lukevmorris** [comment]
So this means that someone must close either the TemplateVariableManager or the CellEditorOverlay in order to navigate away from the DashboardPage (e.g. to the DataExplorer). Seems like it would prevent accidental navigations prior to saving a bunch of work.

**Comment by lukevmorris** [comment]
Code seems ok btw -- just want to clarify intention with ^

**Comment by alexpaxton** [comment]
@lukevmorris yeah going full modal. Seemed strange that you could navigate away mid task, unclear whether it would save or cancel the work done. Thanks for the review 🦀

**Comment by jaredscheib** [comment]
.. "just a modal" 😱

**Pull request merged**
