### PR TITLE
Update INSTALLATION.md

### PR DESCRIPTION
**Pull request by squaresurf**
The default port for chronograf has changed to `10000`.

### CODE REVIEW

**Comment by goller** [comment]
Hey @squaresurf, thanks for your PR!  So, the formerly closed-source chronograf 1.0 used  port 10000.  We've re-envisioned chronograf for 1.1 and made it open-source at this repository.
We are now using 8888 by default, but, that port is configurable at run-time.

However, thank you for taking the time to make a PR, but, I'll need to close it.

**Comment by squaresurf** [comment]
@goller you're right! I had installed chronograf from the apt repo on ubuntu just like telegraf and influxdb so I thought I was on the open source version.

**Comment by goller** [comment]
@squaresurf no worries.  When we move chronograf out of beta, we'll make sure to work on getting the packages updated as well.

**Comment by squaresurf** [comment]
Sounds good. Honestly I really liked chronograf, but it's lack of support for graphs other than a simple line makes it so that I'll use grafana for now. There are some metrics that will need to be stacked at least. Thank you for your hard work. I look forward to following along.

**Comment by goller** [comment]
@squaresurf Yeah, stacked graphs are really nice.  Currently, we support line graphs, simple stat, and line graph with simple stat.  I've added case #751 to create support for stacked graphs.

**Comment by squaresurf** [comment]
Perfect. Thanks!

**Comment by jaredscheib** [comment]
@squaresurf Any particular graphs might you like seeing default to stacked for now, until we add it to the UI as an option?

**Pull request closed without merging**
