### PR TITLE
Fix z-index for options context menu

### PR DESCRIPTION
**Pull request by AbleLincoln**
- [x] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Connect #1643

### The problem
Due to the z-index being set for the entire .dash-graph--options div, when the context menu is shown and overlaps another caret, the caret will display above the context menu.

### The Solution
Move the z-index declaration to the .dash-graph--options-menu ul (removing it from .dash-graph--options div). The z-index is unnecessary for the entire div, it is only needed for the ul so that it displays above the other elements.

### Preview
zindex_chronograf

P.S. This is my first open source contribution. Pretty excited! Please let me know if I did anything incorrectly

### CODE REVIEW

**Comment by jaredscheib** [comment]
Hey @AbleLincoln, thanks for submitting a PR! And congrats on taking the open-source leap :) We're excited to see your PR this morning.

I'll defer to @alexpaxton for a review of your code change, but I would request that you modify your `CHANGELOG` update to follow the style of present tense, active, e.g. `Fix z-index for cell context menu options`. As an aside, this would also be nice for future commit messages (or you could rebase your current messages to follow that style), as that's the style we generally strive to use here.

In general, it's good practice with any open-source contribution to infer (or abide, if explicit) the style for commit messages, PR descriptions, changelog updates, etc.

Thank you again!

**Comment by 121watts** [comment]
Thanks you!

**Comment by AbleLincoln** [comment]
Ok, I've updated the CHANGELOG and PR title. For some reason git is not allowing me to rebase my older commit messages. But I will keep in mind the conventions for any future commits/PRs. Thank you guys for being so helpful and welcoming. I look forward to contributing more

**Comment by alexpaxton** [comment]
We realized that the changelog update was in the previous version's section after asking you to make the change, so we went ahead and put it in the right section (1.3.5) instead of asking you go to back and do it again. Also with the 1.3.4 release some other changelog updates were modified, and those accidentally made it into this branch via the merge commit above, so I corrected that too.

Thank you again, and great work!

**Pull request merged**
