### PR TITLE
Initial IE 11 rendering support

### PR DESCRIPTION
**Pull request by cryptoquick**
- [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [ ] Rebased/mergable
  - [ ] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Connect #

### The problem
Chronograf doesn't even render on IE 11.

### The Solution
Add babel polyfill. Fix a small event error.

### To do
Fix the query builder in the Data Explorer

### CODE REVIEW

**Comment by jaredscheib** [comment]
Nice. Btw, could you add a comment on any code that's specifically dedicated to this purpose that clarifies what it's for? For the babel polyfill and event listener so far, for example.

**Comment by cryptoquick** [comment]
We observed some strangeness in the initial source entry screen on testing, but it wasn't easy to resolve because the app would behave as expected with the console opened. I believe we should merge this, as it provides us with some valuable fixes. Testing should then be implemented. I've opened an issue for this.

**Comment by cryptoquick** [comment]
This is for initial support of at least rendering the application. This a huge improvement over what was there before. We reduced the scope of this to move this along, and so we can merge this, and make it better moving forward.

**Comment by 121watts** [comment]
This solves most but not *all* problems with IE.  Let's get get this in.

**Comment by theone3nu** [comment]
I am getting this error Promise is undefined in IE 11. Any fix for this?

**Pull request merged**
